# Global Workflow Name
name: Build and Deploy Job

# Trigger on push/pull to main branch
on:
  pull_request:
    branches: [develop]
    types: [closed]

# Environment Variables
env:
  AZURE_FUNCTIONAPP_NAME: '<nhodgefuncapp'   
  PYTHON_VERSION: '3.12' 

jobs:
  # Job Name changed to build-and-deploy
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Step 3: Install Dependencies
      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      # Step 4: Deploy to Azure
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_STAGING_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
