name: Swap Function Slots
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  swap-function:
    if: ${{ github.head_ref == 'develop' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: 'Swap the Azure Function'
        run: |
          az functionapp deployment slot swap -g devops -n nhodgefuncapp --slot staging --target-slot production